name: Package Extension
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Install the dependencies
        run: npm install
      - name: Install vsce
        run: npm i -g vsce
      - name: Create VSIX
        run: vsce package
      - name: Archive VSIX
        uses: actions/upload-artifact@v4
        with:
          name: vsix-package
          path: bytestash-*.vsix